### ISSUE TITLE
Error on macOS : com.sun.jna.LastErrorException: [2] No such file or directory

### ISSUE THREAD

**Issue by Alt-er** [drasyl/netty-tun#72]
**env:**
Apple M1 Pro 
macOS Ventura 13.3.1

**Running with debug or java -jar gives the following error:**

➜  target git:(master) sudo java -jar netty-tun-examples.jar echo
Password:
com.sun.jna.LastErrorException: [2] No such file or directory
	at org.drasyl.channel.tun.jna.shared.LibC.ioctl(Native Method)
	at org.drasyl.channel.tun.jna.darwin.DarwinTunDevice.open(DarwinTunDevice.java:111)
	at org.drasyl.channel.tun.TunChannel.doBind(TunChannel.java:114)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:562)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1334)
	at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:506)
	at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:491)
	at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:973)
	at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:260)
	at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:356)
	at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
4月 24, 2023 6:09:13 下午 io.netty.util.internal.PromiseNotificationUtil tryFailure
warning: Failed to mark a promise as failure because it has succeeded already: DefaultChannelPromise@38b64f07(success)
java.lang.IllegalStateException: close() must be invoked after the channel is closed.
	at io.netty.channel.ChannelOutboundBuffer.close(ChannelOutboundBuffer.java:683)
	at io.netty.channel.ChannelOutboundBuffer.close(ChannelOutboundBuffer.java:711)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:736)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:620)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.close(DefaultChannelPipeline.java:1352)
	at io.netty.channel.AbstractChannelHandlerContext.invokeClose(AbstractChannelHandlerContext.java:622)
	at io.netty.channel.AbstractChannelHandlerContext.close(AbstractChannelHandlerContext.java:606)
	at io.netty.channel.AbstractChannelHandlerContext.close(AbstractChannelHandlerContext.java:472)
	at io.netty.channel.DefaultChannelPipeline.close(DefaultChannelPipeline.java:957)
	at io.netty.channel.AbstractChannel.close(AbstractChannel.java:244)
	at io.netty.channel.ChannelFutureListener$2.operationComplete(ChannelFutureListener.java:56)
	at io.netty.channel.ChannelFutureListener$2.operationComplete(ChannelFutureListener.java:52)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
	at io.netty.util.concurrent.DefaultPromise.addListener(DefaultPromise.java:184)
	at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:95)
	at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:30)
	at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:356)
	at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by Alt-er** [comment]
**Switch to the latest :1.3.0-SNAPSHOT**

**Running with debug or java -jar gives the following error:**

➜  target git:(master) ✗ java -jar netty-tun-examples.jar echo            
com.sun.jna.LastErrorException: [14] Bad address
	at org.drasyl.channel.tun.jna.shared.LibC.ioctl(Native Method)
	at org.drasyl.channel.tun.jna.darwin.DarwinTunDevice.open(DarwinTunDevice.java:111)
	at org.drasyl.channel.tun.TunChannel.doBind(TunChannel.java:114)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:562)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1334)
	at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:600)
	at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:579)
	at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:973)
	at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:260)
	at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:356)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
	at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
4月 24, 2023 6:27:59 下午 io.netty.util.internal.PromiseNotificationUtil tryFailure
warning: Failed to mark a promise as failure because it has succeeded already: DefaultChannelPromise@1965209e(success)
java.lang.IllegalStateException: close() must be invoked after the channel is closed.
	at io.netty.channel.ChannelOutboundBuffer.close(ChannelOutboundBuffer.java:693)
	at io.netty.channel.ChannelOutboundBuffer.close(ChannelOutboundBuffer.java:721)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:736)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:620)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.close(DefaultChannelPipeline.java:1352)
	at io.netty.channel.AbstractChannelHandlerContext.invokeClose(AbstractChannelHandlerContext.java:749)
	at io.netty.channel.AbstractChannelHandlerContext.close(AbstractChannelHandlerContext.java:727)
	at io.netty.channel.AbstractChannelHandlerContext.close(AbstractChannelHandlerContext.java:560)
	at io.netty.channel.DefaultChannelPipeline.close(DefaultChannelPipeline.java:957)
	at io.netty.channel.AbstractChannel.close(AbstractChannel.java:244)
	at io.netty.channel.ChannelFutureListener$2.operationComplete(ChannelFutureListener.java:56)
	at io.netty.channel.ChannelFutureListener$2.operationComplete(ChannelFutureListener.java:52)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:590)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:557)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:492)
	at io.netty.util.concurrent.DefaultPromise.addListener(DefaultPromise.java:185)
	at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:95)
	at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:30)
	at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:356)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
	at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by HeikoBornholdt** [comment]
@KevinRoebert can you please look into this? I currently have no Apple silicon available to test this.

**Comment by KevinRoebert** [comment]
> @KevinRoebert can you please look into this? I currently have no Apple silicon available to test this.

Closed. See https://github.com/drasyl/netty-tun-examples/issues/9
